language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1
  - nightly
notifications:
  email: false
allow_failures:
 - julia: nightly

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ParserCombinator"); Pkg.test("ParserCombinator"; coverage=true)'
after_success:
- julia -e 'using Pkg, ParserCombinator; cd(joinpath(dirname(pathof(ParserCombinator)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
